package settings;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.ThreadContext;

import database.DatabaseAccess;
import login.HashPass;
import login.LoginModel;

@WebServlet("/Settings")
public class SettingsServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static final Logger logger = LogManager.getLogger(SettingsServlet.class.getName());
	private String username = "{Placeholder}";
	String oldEmail = "oldEmail@gmail.com";
	String oldPassword = "oldPassword";
	String location = null;

    public SettingsServlet() {
        super();
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession(false);
		if (session != null) {
			username = (String)session.getAttribute("username");
			location = (String)session.getAttribute("location");
		}
		else {
			//response.sendRedirect("Login");
			System.out.println("Session not created - redirect to login");
		}
		
		ThreadContext.put("IP", (InetAddress.getLocalHost()).toString());
		ThreadContext.put("Username", username);
		ThreadContext.put("Location", location);
		logger.debug("entered Settings page");
		ThreadContext.clearAll();
		
		try {
			DatabaseAccess dBA = new DatabaseAccess(1);
			String sqlLine = "SELECT User.Email FROM User INNER JOIN Login ON User.UserID = Login.UserID WHERE Login.Username = \"" + username + "\";";
			ResultSet rs = dBA.getDatabaseData(sqlLine);
			rs.next();
			oldEmail = rs.getString("Email");
			rs.close();
			dBA.close();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		PrintWriter out = response.getWriter();
		out.println("<!DOCTYPE html>"
				+ "<html>"
				+ 	"<head>"
				+ 		"<meta charset='UTF-8'>"
				+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
				+ 		"<!-- Font Mono-Sans -->"
				+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
				+ 		"<!-- Latest compiled and minified CSS -->"
				+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
				+ 		"<!-- Optional theme -->"
				+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
				+ 		"<link rel='stylesheet' href='css/Settings.css'>"
				+ 		"<script src='script/Settings.js'></script>"
				+ 		"<title>Settings</title>"
				+ 	"</head>"
				+ 	"<body>"
				+ 		"<div id='theDiv'>"
				+ 			"<div class='container-fluid' id='Top-Container-Background'>"
				+ 				"<div class='container-fluid' id='Top-Container'>"
				+ 					"<!-- Navigation -->"
				+ 					"<nav class='navbar navbar-default'>"
				+ 						"<div class='container-fluid'>"
				+ 							"<div class='navbar-header'>"
				+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
				+ 							"</div>"
				+ 							"<div class='collapse navbar-collapse'>"
				+ 								"<ul class='nav navbar-nav'>"
				+ 									"<li class='active'><a href='Home'>Home</a></li>"
				+ 									"<li><a href='Directory'>Directory</a></li>"
				+ 								"</ul>"
				+ 								"<ul class='nav navbar-nav navbar-right'>"
				+ 									"<li class='dropdown'>"
				+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
				+ 										"<ul class='dropdown-menu'>"
				+ 											"<li><a href='#'>Setting</a></li>"
				+ 											"<li><a href='Login'>Logout</a></li>"
				+ 										"</ul>"
				+ 									"</li>"
				+ 								"</ul>"
				+ 							"</div>"
				+ 						"</div>"
				+ 					"</nav>"
				+ 				"</div>"
				+ 			"</div>"
				+ 			"<div id='contentDiv'>"
				+ 				"<div id='headerDiv'>"
				+ 					"<h2>Settings</h2>"
				+ 				"</div>"
				+ 				"<div id='aDiv'>"
				+ 					"<div id='setForm'>"
				+ 						"<div id='showName'>"
				+ 							"<div class='categoryDiv'>"
				+ 								"<p>Username</p>"
				+ 							"</div>"
				+ 							"<div class='flexDiv'>"
				+ 								"<p>" + username + "</p>"
				+ 							"</div>"
				+ 						"</div>"
				+ 						"<div id='showEmail'>"
				+							"<form id='emailForm' method='POST'>"
				+ 								"<div class='categoryDiv'>"
				+ 									"<p>Email</p>"
				+ 								"</div>"
				+ 								"<div class='flexDiv'>"
				+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
				+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
				+ 								"</div>"
				+ 								"<div id='changeEmailDiv'>"
				+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
				+ 									"<div id='inputError'>Please enter your email.</div>"
				+ 									"<div id='emailBtnDiv'>"
				+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
				+ 									"</div>"
				+ 								"</div>"
				+							"</form>"
				+ 						"</div>"
				+ 						"<div id='editPass'>"
				+							"<form id='passForm' method='POST'>"
				+ 								"<div class='categoryDiv'>"
				+ 									"<p>Password</p>"
				+ 								"</div>"
				+ 								"<div class='flexDiv'>"
				+ 									"<div id='editPassLinkDiv'>"
				+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
				+ 									"</div>"
				+ 								"</div>"
				+ 								"<div id='changePassDiv'>"
				+ 									"<div id='oldPassDiv' class='flexDiv'>"
				+ 										"<label class='passInputLabel'>Old password: </label>"
				+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
				+ 									"</div>"
				+ 									"<div id='inputPError1'>Password does not match.</div>"
				+ 									"<div id='newPassDiv' class='flexDiv'>"
				+ 										"<label class='passInputLabel'>New password: </label>"
				+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
				+ 									"</div>"
				+ 									"<div id='inputPError2'>Please enter a new password.</div>"
				+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
				+ 										"<label class='passInputLabel'>Confirm password: </label>"
				+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
				+ 									"</div>"
				+ 									"<div id='inputPError3'>Password does not match the new one.</div>"
				+ 									"<div id='passBtnDiv'>"
				+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
				+ 									"</div>"
				+ 								"</div>"
				+							"</form>"
				+ 						"</div>"
				+ 					"</div>"
				+ 				"</div>"
				+ 			"</div>"
				+ 		"</div>"
				+ 	"</body>"
				+ "</html>");
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String inputEmail = request.getParameter("inputEmail");
		String oldPass = request.getParameter("oldPass");
		String newPass = request.getParameter("newPass");
		String confirmNewPass = request.getParameter("confirmNewPass");
		String updateBtn = request.getParameter("updateBtn");
		
		HttpSession session = request.getSession(false);
		if (session != null) {
			username = (String)session.getAttribute("username");
			location = (String)session.getAttribute("location");
		}
		else {
			//response.sendRedirect("Login");
			System.out.println("Session not created - redirect to login");
		}
		try {
			DatabaseAccess dBA = new DatabaseAccess(1);
			String sqlLine = "SELECT User.Password FROM User INNER JOIN Login ON User.UserID = Login.UserID WHERE Login.Username = \"" + username + "\";";
			ResultSet rs = dBA.getDatabaseData(sqlLine);
			rs.next();
			oldPassword = rs.getString("Password");
			rs.close();
			dBA.close();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		System.out.println("doPost - " + oldPassword);
		/*
		if (updateBtn == null) {
			System.out.println("No button clicked");
		}
		*/
		if (updateBtn.equals("emailBtn")) {
			System.out.println("Email button clicked");
			if (inputEmail.equals(oldEmail)) {
				System.out.println("Old email matches with new email");
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='#'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv' style='display:block'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError' style='display:block'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1'>Password does not match.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2'>Please enter a new password.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3'>Does not match new password.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
			else {
				System.out.println("Can change email successfully");
				//Update new email to database
				try {
					DatabaseAccess dBA = new DatabaseAccess(1);
					String sqlLine = "UPDATE Login SET User.email = \"" + inputEmail + "\" WHERE userID = (SELECT UserId FROM User WHERE Login.Username = \"" + username + "\");";
					//String sqlLine = "UPDATE User INNER JOIN Login ON User.UserID = Login.UserID SET User.email = \"" + inputEmail + "\" WHERE Login.Username = \"" + username + "\";";
					ResultSet rs = dBA.getDatabaseData(sqlLine);
					rs.next();
					rs.close();
					dBA.close();
				} catch (ClassNotFoundException e) {
					e.printStackTrace();
				} catch (SQLException e) {
					e.printStackTrace();
				}
				
				ThreadContext.put("IP", (InetAddress.getLocalHost()).toString());
				ThreadContext.put("Username", username);
				ThreadContext.put("Location", location);
				logger.debug("Changed email successfully");
				ThreadContext.clearAll();
				
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						+		"<style>"
						+ 			"#snackbar { min-width: 250px; margin-left: -175px; background-color: #333; color: #FFF; text-align: center; border-radius: 2px; padding: 16px; position: fixed; z-index: 1; left: 50%; bottom: 30px; font-size: 17px; }>"
						+ 		"</style>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='#'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1'>Password does not match.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2'>Please enter a new password.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3'>Does not match new password.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+				"<div id='snackbar'>"
						+					"Email changed successfully"
						+				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
		}
		else if (updateBtn.equals("passBtn")) {
			System.out.println("Password button clicked");
			if (oldPass.contains("<script>") && oldPass.contains("</script>")) {
				ThreadContext.put("IP", (InetAddress.getLocalHost()).toString());
				ThreadContext.put("Username", username);
				ThreadContext.put("Location", location);
				logger.debug("attempted cross-site scripting");
				ThreadContext.clearAll();
				
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						//+		"<style>"
						//+			"#changePassDiv #inputPError1::after { content: ''; position: absolute; bottom: 78%; left: 93%; margin-left: -12px;  border-width: 12px; border-style: solid; border-color: transparent transparent #F74225 transparent; }>'"
						//+ 	"</style>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='#'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv' style='display:block'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1' style='display:block'>Cross-site scripting detected.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2'>Please enter a new password.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3'>Does not match new password.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
			else if (newPass.contains("<script>") && newPass.contains("</script>")) {
				ThreadContext.put("IP", (InetAddress.getLocalHost()).toString());
				ThreadContext.put("Username", username);
				ThreadContext.put("Location", location);
				logger.debug("attempted cross-site scripting");
				ThreadContext.clearAll();
				
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						//+		"<style>"
						//+			"#changePassDiv #inputPError2::after { content: ''; position: absolute; bottom: 56.5%; left: 93%; margin-left: -12px;  border-width: 12px; border-style: solid; border-color: transparent transparent #F74225 transparent; }>'"
						//+ 	"</style>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='#'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv' style='display:block'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1'>Password does not match.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2' style='display:block'>Cross-site scripting detected.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3'>Does not match new password.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
			else if (confirmNewPass.contains("<script>") && confirmNewPass.contains("</script>")) {
				ThreadContext.put("IP", (InetAddress.getLocalHost()).toString());
				ThreadContext.put("Username", username);
				ThreadContext.put("Location", location);
				logger.debug("attempted cross-site scripting");
				ThreadContext.clearAll();
				
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						//+		"<style>"
						//+			"#changePassDiv #inputPError3::after { content: ''; position: absolute; bottom: 35.4%; left: 93%; margin-left: -12px;  border-width: 12px; border-style: solid; border-color: transparent transparent #F74225 transparent; }>'"
						//+ 	"</style>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Purpleboard</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='Settings'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv' style='display:block'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1'>Password does not match.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2'>Please enter a new password.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3' style='display:block'>Cross-site scripting detected.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
			else if (!oldPass.equals(oldPassword)) {
				System.out.println("Wrong old password");
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						//+		"<style>"
						//+			"#changePassDiv #inputPError1::after { content: ''; position: absolute; bottom: 78%; left: 93%; margin-left: -12px;  border-width: 12px; border-style: solid; border-color: transparent transparent #F74225 transparent; }>'"
						//+ 	"</style>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='#'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv' style='display:block'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1' style='display:block'>Password does not match.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2'>Please enter a new password.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3'>Does not match new password.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
			else if (oldPass.equals(newPass)) {
				System.out.println("Old password same as new password");
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						//+		"<style>"
						//+			"#changePassDiv #inputPError2::after { content: ''; position: absolute; bottom: 56.5%; left: 93%; margin-left: -12px;  border-width: 12px; border-style: solid; border-color: transparent transparent #F74225 transparent; }>'"
						//+ 	"</style>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='#'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv' style='display:block'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1'>Password does not match.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2' style='display:block'>Please enter a new password.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3'>Does not match new password.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
			else if (!newPass.equals(confirmNewPass)) {
				System.out.println("Does not match new password");
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						//+		"<style>"
						//+			"#changePassDiv #inputPError3::after { content: ''; position: absolute; bottom: 35.4%; left: 93%; margin-left: -12px;  border-width: 12px; border-style: solid; border-color: transparent transparent #F74225 transparent; }>'"
						//+ 	"</style>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='#'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv' style='display:block'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1'>Password does not match.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2'>Please enter a new password.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3' style='display:block'>Does not match new password.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
			else if (oldPass.equals(oldPassword) && !oldPass.equals(newPass) && newPass.equals(confirmNewPass)) {
				System.out.println("Can change password successfully");
				Base64.Encoder enc = Base64.getEncoder();
				HashPass HP = new HashPass();
				byte [] newSalt = HP.createSalt();
				String newSaltStr = enc.encodeToString(newSalt);
				String newHashedPassword = HP.getHashedPassword(confirmNewPass, newSalt);
				//Update the newly generated salt and hashed password to database given the username
				try {
					DatabaseAccess dBA = new DatabaseAccess(1);
					String sqlLine1 = "UPDATE Login SET Login.salt = \"" + newSaltStr + "\" WHERE userID = (SELECT UserId FROM User WHERE Login.username = \"" + username + "\");";
					String sqlLine2 = "UPDATE Login SET Login.password = \"" + newHashedPassword + "\" WHERE userID = (SELECT UserId FROM User WHERE Login.username = \"" + username + "\");";
					//String sqlLine = "UPDATE Login SET User.email = \"" + inputEmail + "\" WHERE userID = (SELECT UserId FROM User WHERE Login.Username = \"" + username + "\");";
					//String sqlLine1 = "UPDATE Login SET salt = \"" + newSaltStr + "\" WHERE username = \"" + username + "\";";
					//String sqlLine2 = "UPDATE Login SET password = \"" + newHashedPassword + "\" WHERE username = \"" + username + "\";";
					ResultSet rs1 = dBA.getDatabaseData(sqlLine1);
					rs1.next();
					ResultSet rs2 = dBA.getDatabaseData(sqlLine2);
					rs2.next();
					rs2.close();
					rs1.close();
					dBA.close();
				} catch (ClassNotFoundException e) {
					e.printStackTrace();
				} catch (SQLException e) {
					e.printStackTrace();
				}
				
				ThreadContext.put("IP", (InetAddress.getLocalHost()).toString());
				ThreadContext.put("Username", username);
				ThreadContext.put("Location", location);
				logger.debug("changed password successfully");
				ThreadContext.clearAll();
				
				PrintWriter out = response.getWriter();
				out.println("<!DOCTYPE html>"
						+ "<html>"
						+ 	"<head>"
						+ 		"<meta charset='UTF-8'>"
						+ 		"<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>"
						+ 		"<!-- Font Mono-Sans -->"
						+ 		"<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>"
						+ 		"<!-- Latest compiled and minified CSS -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>"
						+ 		"<!-- Optional theme -->"
						+ 		"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' integrity='sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp' crossorigin='anonymous'>"
						+ 		"<link rel='stylesheet' href='css/Settings.css'>"
						+ 		"<script src='script/Settings.js'></script>"
						+ 		"<title>Settings</title>"
						+		"<style>"
						+ 			"#snackbar { min-width: 250px; margin-left: -190px; background-color: #333; color: #FFF; text-align: center; border-radius: 2px; padding: 16px; position: fixed; z-index: 1; left: 50%; bottom: 30px; font-size: 17px; }>"
						+ 		"</style>"
						+ 	"</head>"
						+ 	"<body>"
						+ 		"<div id='theDiv'>"
						+ 			"<div class='container-fluid' id='Top-Container-Background'>"
						+ 				"<div class='container-fluid' id='Top-Container'>"
						+ 					"<!-- Navigation -->"
						+ 					"<nav class='navbar navbar-default'>"
						+ 						"<div class='container-fluid'>"
						+ 							"<div class='navbar-header'>"
						+ 								"<a class='navbar-brand' href='#'>Bas?</a>"
						+ 							"</div>"
						+ 							"<div class='collapse navbar-collapse'>"
						+ 								"<ul class='nav navbar-nav'>"
						+ 									"<li class='active'><a href='Home'>Home</a></li>"
						+ 									"<li><a href='Directory'>Directory</a></li>"
						+ 								"</ul>"
						+ 								"<ul class='nav navbar-nav navbar-right'>"
						+ 									"<li class='dropdown'>"
						+ 										"<a class='dropdown-toggle' data-toggle='dropdown' href='#'>Welcome, Bob. </a>"
						+ 										"<ul class='dropdown-menu'>"
						+ 											"<li><a href='#'>Setting</a></li>"
						+ 											"<li><a href='Login'>Logout</a></li>"
						+ 										"</ul>"
						+ 									"</li>"
						+ 								"</ul>"
						+ 							"</div>"
						+ 						"</div>"
						+ 					"</nav>"
						+ 				"</div>"
						+ 			"</div>"
						+ 			"<div id='contentDiv'>"
						+ 				"<div id='headerDiv'>"
						+ 					"<h2>Settings</h2>"
						+ 				"</div>"
						+ 				"<div id='aDiv'>"
						+ 					"<div id='setForm'>"
						+ 						"<div id='showName'>"
						+ 							"<div class='categoryDiv'>"
						+ 								"<p>Username</p>"
						+ 							"</div>"
						+ 							"<div class='flexDiv'>"
						+ 								"<p>" + username + "</p>"
						+ 							"</div>"
						+ 						"</div>"
						+ 						"<div id='showEmail'>"
						+							"<form id='emailForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Email</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<p id='showPEmail'>" + oldEmail + "</p>"
						+ 									"<span id='editEmailLink' onclick='showChangeEmailDiv()'>Edit</span>"
						+ 								"</div>"
						+ 								"<div id='changeEmailDiv'>"
						+ 									"<input type='email' id='inputEmail' name='inputEmail' required>"
						+ 									"<div id='inputError'>Please enter your email.</div>"
						+ 									"<div id='emailBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='emailBtn' id='emailBtn'>Update email</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 						"<div id='editPass'>"
						+							"<form id='passForm' method='POST'>"
						+ 								"<div class='categoryDiv'>"
						+ 									"<p>Password</p>"
						+ 								"</div>"
						+ 								"<div class='flexDiv'>"
						+ 									"<div id='editPassLinkDiv'>"
						+ 										"<span id='editPassLink' onclick='showChangePassDiv()'>Click to change password</span>"
						+ 									"</div>"
						+ 								"</div>"
						+ 								"<div id='changePassDiv'>"
						+ 									"<div id='oldPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Old password: </label>"
						+ 										"<input type='password' id='oldPass' class='passInput' name='oldPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError1'>Password does not match.</div>"
						+ 									"<div id='newPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>New password: </label>"
						+ 										"<input type='password' id='newPass' class='passInput' name='newPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError2'>Please enter a new password.</div>"
						+ 									"<div id='confirmNewPassDiv' class='flexDiv'>"
						+ 										"<label class='passInputLabel'>Confirm password: </label>"
						+ 										"<input type='password' id='confirmNewPass' class='passInput' name='confirmNewPass' required>"
						+ 									"</div>"
						+ 									"<div id='inputPError3'>Does not match new password.</div>"
						+ 									"<div id='passBtnDiv'>"
						+ 										"<button type='submit' name='updateBtn' value='passBtn' id='passBtn'>Update password</button>"
						+ 									"</div>"
						+ 								"</div>"
						+							"</form>"
						+ 						"</div>"
						+ 					"</div>"
						+ 				"</div>"
						+				"<div id='snackbar'>"
						+					"Password changed successfully"
						+				"</div>"
						+ 			"</div>"
						+ 		"</div>"
						+ 	"</body>"
						+ "</html>");
			}
		}
		
	}

}
